site_name: data2bids v3.1
site_author: Greydon Gilmore

# Repository
repo_name: GitHub
repo_url: https://github.com/greydongilmore/data2bids-site
edit_uri: https://github.com/greydongilmore/data2bids-site/blob/master/docs

# Copyright
copyright: Copyright &copy; 2020 Greydon Gilmore

# Configuration
dev_addr: 127.0.0.1:7000
use_directory_urls: false
theme:
  name: material
  custom_dir: material
  palette:
    scheme: 
    primary: red
    accent: red
  logo: img/edf2bids_white_icon.svg
  favicon: img/edf2bids_icon.svg

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  
# Plugins
plugins:
  - search

extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js

nav:
  - Home: index.md
  - Installation: installation.md
  - Run data2bids:
    - Overview: run_data2bids/01_overview.md
    - Definitions: run_data2bids/02_definitions.md
    - data2bids Settings: run_data2bids/03_edf2bids_settings.md
    - Export from NeuroWorks: run_data2bids/04_neuroworks_export.md
    - Input Directory Setup: run_data2bids/05_input_dir_setup.md
    - Imaging Directory Setup: run_data2bids/055_imaging_dir_setup.md
    - Check EDF Type: run_data2bids/06_check_edf_type.md
    - Run Conversion: run_data2bids/07_run_conversion.md
    - Output Directory Structure: run_data2bids/08_output_structure.md
    - SPReD Upload [EpLink]: run_data2bids/09_spred_upload.md
  - Run seeg2bids:
    - Overview: run_seeg2bids/01_overview.md
    - Output: run_seeg2bids/05_output.md
  - Product Manuals: manuals.md