# Project information
site_name: edf2bids
site_author: Greydon Gilmore

# Repository
repo_name: GitHub
repo_url: https://github.com/greydongilmore/edf2bids-site
edit_uri: https://github.com/greydongilmore/edf2bids-site/issues/new

# Copyright
copyright: Copyright &copy; 2020 Greydon Gilmore

# Configuration
dev_addr: 127.0.0.1:7000
theme:
  name: material
  custom_dir: material
  features:
    - tabs
  palette:
    primary: blue grey
    accent: blue
  logo: img/edf2bids_icon.svg
  favicon: img/favicon.ico

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
  
# Plugins
plugins:
  - search